### ISSUE TITLE
Wrong workspace in answer from server: <?xml version="1.0" encoding="UTF-8" standalone="no"?>

### ISSUE THREAD

**Issue by oste** [jackalope/jackalope-jackrabbit#121]
I am running Jackrabbit under Tomcat after following this https://github.com/jackalope/jackalope/wiki/Running-jackrabbit-in-tomcat-with-mysql

My Jackrabbit server is running normally and can be accessed at url:  http://localhost:8080/jackrabbit/repository/default however when I run a command from the command line or access a page on the site I am getting this error.

```
[PHPCR\RepositoryException]
  Wrong workspace in answer from server: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
  <D:multistatus xmlns:D="DAV:"><D:response><D:href>http://localhost:8080/jackrabbit/repository/default/</D:href><D:propstat><D:prop><D:workspace/><dcr:workspaceName xmlns:dcr="http://www.day.com/jcr/webdav/1.0"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:stat
  us></D:propstat></D:response></D:multistatus>
```

The cmf-sandbox also gives me this same error so that should rule out any user error.

**Comment by lsmith77** [comment]
@uwej711 / @dbu do you have a hint here?

**Comment by dbu** [comment]
there is a 404 in this url. what strikes me as odd is that the href for the workspace ends with /, not sure if that is normal... otherwise, did you try to run jackrabbit with java -jar to see if its the client or the server that messes up? maybe there is a typo or when running inside tomcat you need to specify that there should be a default workspace?

**Comment by oste** [comment]
A couple interesting things to note. If I set ```jackalope.check_login_on_server: false``` I get:
```
HTTP 404 Path Not Found: REPORT
--uri: --
array (
  0 => 'http://localhost:8080/jackrabbit/repository/default/jcr:root',
)
```

If I set the ```phpcr_workspace: test``` I get
```
HTTP 404: test
```

**Comment by lsmith77** [comment]
can you paste your phpcr config?

**Comment by oste** [comment]
As I mentioned setting ```jackalope.check_login_on_server: true``` causes the original issue.

```
    phpcr_backend:
        type: jackrabbit
        url:  http://localhost:8080/jackrabbit/repository
        parameters:
            jackalope.check_login_on_server: false
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
```
